// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNWR83rq-y_wxfsFd85dazjbAoL8Kn_k0',
    appId: '1:797566802074:web:814a0ea17d6face08ce723',
    messagingSenderId: '797566802074',
    projectId: 'gencoff-app',
    authDomain: 'gencoff-app.firebaseapp.com',
    storageBucket: 'gencoff-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6_3Px_Uh9y-W0d0CHMdf_cLyB-iUuLCQ',
    appId: '1:797566802074:android:d8d3764c77f6ea908ce723',
    messagingSenderId: '797566802074',
    projectId: 'gencoff-app',
    storageBucket: 'gencoff-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgj9BwucJYcjXQ_l3g7Jpt1_IBg2rsqCY',
    appId: '1:797566802074:ios:d4ad38bbe33d89d18ce723',
    messagingSenderId: '797566802074',
    projectId: 'gencoff-app',
    storageBucket: 'gencoff-app.appspot.com',
    iosBundleId: 'com.example.gencoffApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgj9BwucJYcjXQ_l3g7Jpt1_IBg2rsqCY',
    appId: '1:797566802074:ios:eee5ec9a74c5a5e98ce723',
    messagingSenderId: '797566802074',
    projectId: 'gencoff-app',
    storageBucket: 'gencoff-app.appspot.com',
    iosBundleId: 'com.example.gencoffApp.RunnerTests',
  );
}
